<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            ['id' => 1,  'title' => 'Болт М6х20 оцинкованный',                'title_print' => null, 'store_id' => 4,  'quantity' => null],
            ['id' => 2,  'title' => 'Болт М8х25 с гайкой и шайбой',           'title_print' => null, 'store_id' => 5,  'quantity' => null],
            ['id' => 3,  'title' => 'Болт М10х30 высокопрочный',              'title_print' => null, 'store_id' => 6,  'quantity' => null],
            ['id' => 4,  'title' => 'Болт М12х40 с шестигранной головкой',    'title_print' => null, 'store_id' => 10, 'quantity' => null],
            ['id' => 5,  'title' => 'Болт М14х50 нержавеющий',                'title_print' => null, 'store_id' => 11, 'quantity' => null],
            ['id' => 6,  'title' => 'Болт М16х60 оцинкованный',               'title_print' => null, 'store_id' => 12, 'quantity' => 99],
            ['id' => 7,  'title' => 'Болт М5х16 с потайной головкой',         'title_print' => null, 'store_id' => 16, 'quantity' => null],
            ['id' => 8,  'title' => 'Болт фундаментный 12х200',               'title_print' => null, 'store_id' => 17, 'quantity' => null],
            ['id' => 9,  'title' => 'Болт анкерный М10х100',                  'title_print' => null, 'store_id' => 18, 'quantity' => null],
            ['id' => 10, 'title' => 'Болт мебельный М8х40',                   'title_print' => null, 'store_id' => 4,  'quantity' => null],
            ['id' => 11, 'title' => 'Шуруп 3.5х25 универсальный',             'title_print' => null, 'store_id' => 5,  'quantity' => null],
            ['id' => 12, 'title' => 'Шуруп 4х35 оцинкованный',                'title_print' => null, 'store_id' => 6,  'quantity' => null],
            ['id' => 13, 'title' => 'Шуруп 5х50 по дереву',                   'title_print' => null, 'store_id' => 10, 'quantity' => null],
            ['id' => 14, 'title' => 'Шуруп кровельный 4.8х35',                'title_print' => null, 'store_id' => 11, 'quantity' => null],
            ['id' => 15, 'title' => 'Шуруп с потайной головкой 3х20',         'title_print' => null, 'store_id' => 12, 'quantity' => null],
            ['id' => 16, 'title' => 'Шуруп с прессшайбой 4.2х16',             'title_print' => null, 'store_id' => 16, 'quantity' => null],
            ['id' => 17, 'title' => 'Шуруп глухарь 8х120',                    'title_print' => null, 'store_id' => 17, 'quantity' => null],
            ['id' => 18, 'title' => 'Шуруп гипсокартонный 3.5х25',            'title_print' => null, 'store_id' => 18, 'quantity' => null],
            ['id' => 19, 'title' => 'Шуруп с шестигранной головкой 6х60',     'title_print' => null, 'store_id' => 4,  'quantity' => null],
            ['id' => 20, 'title' => 'Шуруп нержавеющий 4х40',                 'title_print' => null, 'store_id' => 5,  'quantity' => null],
            ['id' => 21, 'title' => 'Гайка М6 шестигранная',                  'title_print' => null, 'store_id' => 6,  'quantity' => null],
            ['id' => 22, 'title' => 'Гайка М8 самоконтрящаяся',               'title_print' => null, 'store_id' => 10, 'quantity' => null],
            ['id' => 23, 'title' => 'Гайка М10 с фланцем',                    'title_print' => null, 'store_id' => 11, 'quantity' => null],
            ['id' => 24, 'title' => 'Гайка М12 колпачковая',                  'title_print' => null, 'store_id' => 12, 'quantity' => null],
            ['id' => 25, 'title' => 'Гайка М14 прорезная',                    'title_print' => null, 'store_id' => 16, 'quantity' => null],
            ['id' => 26, 'title' => 'Гайка М16 рым-гайка',                   'title_print' => null, 'store_id' => 17, 'quantity' => null],
            ['id' => 27, 'title' => 'Гайка М4 барашковая',                    'title_print' => null, 'store_id' => 18, 'quantity' => null],
            ['id' => 28, 'title' => 'Гайка М5 квадратная',                    'title_print' => null, 'store_id' => 4,  'quantity' => null],
            ['id' => 29, 'title' => 'Гайка М20 соединительная',               'title_print' => null, 'store_id' => 5,  'quantity' => null],
            ['id' => 30, 'title' => 'Гайка М8 фланцевая широкая',             'title_print' => null, 'store_id' => 6,  'quantity' => null],
            ['id' => 31, 'title' => 'Шайба плоская М6',                       'title_print' => null, 'store_id' => 10, 'quantity' => null],
            ['id' => 32, 'title' => 'Шайба гровер М8',                        'title_print' => null, 'store_id' => 11, 'quantity' => null],
            ['id' => 33, 'title' => 'Шайба пружинная М10',                    'title_print' => null, 'store_id' => 12, 'quantity' => null],
            ['id' => 34, 'title' => 'Шайба увеличенная М12',                  'title_print' => null, 'store_id' => 16, 'quantity' => null],
            ['id' => 35, 'title' => 'Шайба стопорная М14',                    'title_print' => null, 'store_id' => 17, 'quantity' => null],
            ['id' => 36, 'title' => 'Шайба кузовная М8',                      'title_print' => null, 'store_id' => 18, 'quantity' => null],
            ['id' => 37, 'title' => 'Шайба медная 10мм',                      'title_print' => null, 'store_id' => 4,  'quantity' => null],
            ['id' => 38, 'title' => 'Шайба термостойкая М16',                 'title_print' => null, 'store_id' => 5,  'quantity' => null],
            ['id' => 39, 'title' => 'Шайба текстолитовая М20',                'title_print' => null, 'store_id' => 6,  'quantity' => null],
            ['id' => 40, 'title' => 'Шайба резиновая уплотнительная 8мм',     'title_print' => null, 'store_id' => 10, 'quantity' => null],
            ['id' => 41, 'title' => 'Винт М3х10 с цилиндрической головкой',   'title_print' => null, 'store_id' => 11, 'quantity' => null],
            ['id' => 42, 'title' => 'Винт М4х16 с крестообразным шлицем',     'title_print' => null, 'store_id' => 12, 'quantity' => null],
            ['id' => 43, 'title' => 'Винт М5х20 установочный',                'title_print' => null, 'store_id' => 16, 'quantity' => null],
            ['id' => 44, 'title' => 'Винт М6х25 с внутренним шестигранником', 'title_print' => null, 'store_id' => 17, 'quantity' => null],
            ['id' => 45, 'title' => 'Винт М8х30 мебельный конфирмат',         'title_print' => null, 'store_id' => 18, 'quantity' => null],
            ['id' => 46, 'title' => 'Винт М2.5х8 с полукруглой головкой',     'title_print' => null, 'store_id' => 4,  'quantity' => null],
            ['id' => 47, 'title' => 'Винт М3х12 с потайной головкой',         'title_print' => null, 'store_id' => 5,  'quantity' => null],
            ['id' => 48, 'title' => 'Винт стопорный М4х6',                    'title_print' => null, 'store_id' => 6,  'quantity' => null],
            ['id' => 49, 'title' => 'Винт регулировочный М6х40',              'title_print' => null, 'store_id' => 10, 'quantity' => null],
            ['id' => 50, 'title' => 'Винт невыпадающий М3х10',                'title_print' => null, 'store_id' => 11, 'quantity' => null],
            ['id' => 51, 'title' => 'Заклёпка вытяжная 3.2х8 алюминий',       'title_print' => null, 'store_id' => 12, 'quantity' => null],
            ['id' => 52, 'title' => 'Заклёпка вытяжная 4х10 сталь',           'title_print' => null, 'store_id' => 16, 'quantity' => null],
            ['id' => 53, 'title' => 'Заклёпка вытяжная 4.8х12 нерж',          'title_print' => null, 'store_id' => 17, 'quantity' => null],
            ['id' => 54, 'title' => 'Заклёпка резьбовая М6',                  'title_print' => null, 'store_id' => 18, 'quantity' => null],
            ['id' => 55, 'title' => 'Заклёпка под молоток 5х20',             'title_print' => null, 'store_id' => 4,  'quantity' => null],
            ['id' => 56, 'title' => 'Заклёпка пистонная 3х6',                'title_print' => null, 'store_id' => 5,  'quantity' => null],
            ['id' => 57, 'title' => 'Заклёпка вытяжная 4.8х16 оцинк',         'title_print' => null, 'store_id' => 6,  'quantity' => null],
            ['id' => 58, 'title' => 'Заклёпка вытяжная 5х14',                 'title_print' => null, 'store_id' => 10, 'quantity' => null],
            ['id' => 59, 'title' => 'Заклёпка гаечная М8',                    'title_print' => null, 'store_id' => 11, 'quantity' => null],
            ['id' => 60, 'title' => 'Заклёпка гаечная М10 рифлёная',          'title_print' => null, 'store_id' => 12, 'quantity' => null],
            ['id' => 61, 'title' => 'Дюбель 6х30 распорный',                  'title_print' => null, 'store_id' => 16, 'quantity' => null],
            ['id' => 62, 'title' => 'Дюбель 8х40 универсальный',              'title_print' => null, 'store_id' => 17, 'quantity' => null],
            ['id' => 63, 'title' => 'Дюбель 10х50 для газобетона',            'title_print' => null, 'store_id' => 18, 'quantity' => null],
            ['id' => 64, 'title' => 'Дюбель-гвоздь 6х40',                     'title_print' => null, 'store_id' => 4,  'quantity' => null],
            ['id' => 65, 'title' => 'Дюбель рамный 10х100',                   'title_print' => null, 'store_id' => 5,  'quantity' => null],
            ['id' => 66, 'title' => 'Дюбель потолочный 6х35',                 'title_print' => null, 'store_id' => 6,  'quantity' => null],
            ['id' => 67, 'title' => 'Дюбель бабочка 8х50',                    'title_print' => null, 'store_id' => 10, 'quantity' => null],
            ['id' => 68, 'title' => 'Дюбель химический для бетона',           'title_print' => null, 'store_id' => 11, 'quantity' => null],
            ['id' => 69, 'title' => 'Дюбель фасадный 10х140',                 'title_print' => null, 'store_id' => 12, 'quantity' => null],
            ['id' => 70, 'title' => 'Дюбель пружинный 4х32',                  'title_print' => null, 'store_id' => 16, 'quantity' => null],
            ['id' => 71, 'title' => 'Хомут червячный 12-22мм',                'title_print' => null, 'store_id' => 17, 'quantity' => null],
            ['id' => 72, 'title' => 'Хомут червячный 20-32мм',                'title_print' => null, 'store_id' => 18, 'quantity' => null],
            ['id' => 73, 'title' => 'Хомут червячный 32-50мм',                'title_print' => null, 'store_id' => 4,  'quantity' => null],
            ['id' => 74, 'title' => 'Хомут силовой 50-70мм',                  'title_print' => null, 'store_id' => 5,  'quantity' => null],
            ['id' => 75, 'title' => 'Хомут пластиковый 2.5х100',              'title_print' => null, 'store_id' => 6,  'quantity' => null],
            ['id' => 76, 'title' => 'Хомут нейлоновый стяжка 3.6х200',        'title_print' => null, 'store_id' => 10, 'quantity' => null],
            ['id' => 77, 'title' => 'Хомут металлический 25-40мм',            'title_print' => null, 'store_id' => 11, 'quantity' => null],
            ['id' => 78, 'title' => 'Хомут сантехнический 1/2 дюйма',         'title_print' => null, 'store_id' => 12, 'quantity' => null],
            ['id' => 79, 'title' => 'Хомут трубный 3/4 дюйма',                'title_print' => null, 'store_id' => 16, 'quantity' => null],
            ['id' => 80, 'title' => 'Хомут дюбельный 16мм',                   'title_print' => null, 'store_id' => 17, 'quantity' => null],
            ['id' => 81, 'title' => 'Скоба такелажная 6мм',                   'title_print' => null, 'store_id' => 18, 'quantity' => null],
            ['id' => 82, 'title' => 'Скоба строительная 8мм',                 'title_print' => null, 'store_id' => 4,  'quantity' => null],
            ['id' => 83, 'title' => 'Скоба металлическая для бруса',          'title_print' => null, 'store_id' => 5,  'quantity' => null],
            ['id' => 84, 'title' => 'Скоба мебельная уголок 30х30',           'title_print' => null, 'store_id' => 6,  'quantity' => null],
            ['id' => 85, 'title' => 'Скоба строительная оцинкованная 10мм',   'title_print' => null, 'store_id' => 10, 'quantity' => null],
            ['id' => 86, 'title' => 'Гвоздь строительный 2.5х50',             'title_print' => null, 'store_id' => 11, 'quantity' => null],
            ['id' => 87, 'title' => 'Гвоздь финишный 2х30',                   'title_print' => null, 'store_id' => 12, 'quantity' => null],
            ['id' => 88, 'title' => 'Гвоздь кровельный 3.5х25',               'title_print' => null, 'store_id' => 16, 'quantity' => null],
            ['id' => 89, 'title' => 'Гвоздь шиферный 4х100',                  'title_print' => null, 'store_id' => 17, 'quantity' => null],
            ['id' => 90, 'title' => 'Гвоздь дюбель 2.8х40',                   'title_print' => null, 'store_id' => 18, 'quantity' => null],
            ['id' => 91, 'title' => 'Анкер-клин 10х100',                      'title_print' => null, 'store_id' => 4,  'quantity' => null],
            ['id' => 92, 'title' => 'Анкер латунный цанга М8',                'title_print' => null, 'store_id' => 5,  'quantity' => null],
            ['id' => 93, 'title' => 'Анкер рамный 12х150',                    'title_print' => null, 'store_id' => 6,  'quantity' => null],
            ['id' => 94, 'title' => 'Анкер потолочный металлический М6',     'title_print' => null, 'store_id' => 10, 'quantity' => null],
            ['id' => 95, 'title' => 'Анкер химический капсула М12',           'title_print' => null, 'store_id' => 11, 'quantity' => null],
            ['id' => 96, 'title' => 'Шпилька резьбовая М8х1000',              'title_print' => null, 'store_id' => 12, 'quantity' => null],
            ['id' => 97, 'title' => 'Шпилька резьбовая М10х2000',             'title_print' => null, 'store_id' => 16, 'quantity' => null],
            ['id' => 98, 'title' => 'Шпилька резьбовая М12х1000 оцинк',       'title_print' => null, 'store_id' => 17, 'quantity' => null],
            ['id' => 99, 'title' => 'Шпилька резьбовая М16х2000',             'title_print' => null, 'store_id' => 18, 'quantity' => null],
            ['id' => 100,'title' => 'Шпилька резьбовая М20х1000 стальная',    'title_print' => null, 'store_id' => 4,  'quantity' => null],
            ['id' => 101,'title' => 'Лезвия для ножа трапециевидные "Vira"',  'title_print' => null, 'store_id' => 8,  'quantity' => 50],
            ['id' => 102,'title' => 'Лезвия "Vira" трапециевидные, код ОЗОН', 'title_print' => null, 'store_id' => null, 'quantity' => 32],
            ['id' => 103,'title' => 'Лезвия "Vira", код data-matrix',         'title_print' => null, 'store_id' => null, 'quantity' => 14],
        ];

        foreach ($items as $item) {
            DB::table('item')->updateOrInsert(
                ['id' => $item['id']],
                [
                    'title' => $item['title'],
                    'title_print' => $item['title_print'],
                    'store_id' => $item['store_id'],
                    'quantity' => $item['quantity'],
                    'updated_at' => now(),
                ]
            );
        }
    }
}
