apiVersion: v1
kind: ConfigMap
metadata:
  name: home-store-config
  namespace: home-store
data:
  # API configuration
  API_HOST: "api-service"
  API_PORT: "80"
  
  # www (Nuxt) configuration
  NUXT_PUBLIC_API_BASE_URL: "http://api-service"
  HOST: "0.0.0.0"
  PORT: "3000"
