apiVersion: v1
kind: ConfigMap
metadata:
  name: home-store-config
  namespace: home-store
data:
  APP_NAME: "Laravel"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "http://store.dev11.ru"
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "warning"
  SESSION_DRIVER: "database"
  QUEUE_CONNECTION: "database"
  CACHE_STORE: "database"
  FILESYSTEM_DISK: "local"
  DB_CONNECTION: "pgsql"
  DB_HOST: "home-store-postgres"
  DB_PORT: "5432"
  DB_DATABASE: "home_store"
  NUXT_PUBLIC_API_BASE_URL: "http://api.dev11.ru"