apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: home-store
data:
  init.sql: |
    CREATE TEXT SEARCH DICTIONARY russian_hunspell (
        TEMPLATE = ispell,
        dictfile = ru_ru,
        afffile = ru_ru,
        stopwords = russian
    );
    CREATE TEXT SEARCH CONFIGURATION russian_hunspell (COPY = russian);
    ALTER TEXT SEARCH CONFIGURATION russian_hunspell
        ALTER MAPPING FOR hword, hword_part, word WITH russian_hunspell, russian_stem;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: home-store
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: home-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: home_store
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: home-store-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: home-store-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
            - name: hunspell-aff
              mountPath: /usr/share/postgresql/16/tsearch_data/ru_ru.affix
            - name: hunspell-dic
              mountPath: /usr/share/postgresql/16/tsearch_data/ru_ru.dict
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d/001-init.sql
              subPath: init.sql
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: hunspell-aff
          hostPath:
            path: /data/home-store/tsearch_data/ru_ru.affix
            type: File
        - name: hunspell-dic
          hostPath:
            path: /data/home-store/tsearch_data/ru_ru.dict
            type: File
        - name: postgres-init
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: home-store-postgres
  namespace: home-store
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432