apiVersion: v1
kind: Secret
metadata:
  name: home-store-secrets
  namespace: home-store
type: Opaque
stringData:
  APP_KEY: base64:cWvsj/dGDTT+pVsOF6QQ7snf4O766yJsRi4KFkzTtHg=
  DB_USERNAME: home_store
  DB_PASSWORD: home_store
  AWS_ACCESS_KEY_ID: 1UQ08DSTE7TW2NV1INNG
  AWS_SECRET_ACCESS_KEY: 9NsDourR18CzpzADdLBwUThxUIDgXqgRikBG3yry
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: 58e49e17d3c1-homestore-dev
  AWS_ENDPOINT: https://s3.ru1.storage.beget.cloud
  AWS_USE_PATH_STYLE_ENDPOINT: "true"