apiVersion: v1
kind: Secret
metadata:
  name: home-store-secrets
  namespace: home-store
type: Opaque
stringData:
  APP_KEY: base64:cWvsj/dGDTT+pVsOF6QQ7snf4O766yJsRi4KFkzTtHg=
  DB_USERNAME: home_store
  DB_PASSWORD: home_store