apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
  namespace: home-store
  labels:
    app: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: www
          image: registry.cubicat.ru/home-store/home-store-www:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          env:
            - name: NUXT_PUBLIC_API_BASE_URL
              value: http://api.dev11.ru
            - name: API_URL
              value: https://api.dev11.ru
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "3000"