server {
    listen 80;
    server_name _;
    index index.php index.html;
    error_log /dev/stderr notice;
    access_log /dev/stdout;

    root /var/www/html/public;

    client_max_body_size 25m;
    client_body_buffer_size 16k;
    client_body_timeout 120;

    location = /nginx-health {
        access_log off;
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass api-app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.(ht|env)$ {
        deny all;
    }
}